/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import dao.GuestDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.Guest;

/**
 *
 * @author abc
 */
public class GuestPanel extends javax.swing.JPanel {
    private GuestDAO gDAO = new  GuestDAO();
    private List<Guest> listGuest;

    /**
     * Creates new form Guest
     */
    
    private void setTable() {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        jTable1.setModel(defaultTableModel);
        ListSelectionModel listSelectionModel = jTable1.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        defaultTableModel.addColumn("STT");
        defaultTableModel.addColumn("Mã Khách Hàng");
        defaultTableModel.addColumn("Họ tên");
        defaultTableModel.addColumn("Địa chỉ");
        defaultTableModel.addColumn("Số điện thoại");
        defaultTableModel.addColumn("Email");
        listGuest = gDAO.getAllGuests();

        // Duyệt qua danh sách products và thêm vào bảng
        int stt = 1; // Biến đánh số thứ tự
        for (Guest g : listGuest) {
            Object[] row = new Object[6];
            row[0] = stt++;  // Số thứ tự
            row[1] = g.getID();
            row[2] = g.getName();
            row[3] = g.getAddress();
            row[4] = g.getSDT();
            row[5] = g.getEmail();
            defaultTableModel.addRow(row); // Thêm hàng vào bảng
        }

    }
    
    public GuestPanel() {
        initComponents();
        setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_dialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        add_idlb = new javax.swing.JLabel();
        add_quantitylb = new javax.swing.JLabel();
        add_namelb = new javax.swing.JLabel();
        add_brandlb = new javax.swing.JLabel();
        add_pricelb = new javax.swing.JLabel();
        add_emailText = new javax.swing.JTextField();
        add_idText = new javax.swing.JTextField();
        add_nameText = new javax.swing.JTextField();
        add_addressText = new javax.swing.JTextField();
        add_SdtText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        edit_dialog = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        add_idlb1 = new javax.swing.JLabel();
        add_quantitylb1 = new javax.swing.JLabel();
        add_namelb1 = new javax.swing.JLabel();
        add_brandlb1 = new javax.swing.JLabel();
        add_pricelb1 = new javax.swing.JLabel();
        edit_emailText = new javax.swing.JTextField();
        edit_nameText = new javax.swing.JTextField();
        edit_addressText = new javax.swing.JTextField();
        edit_SdtText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        edit_idLable = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addBtn_Guest = new javax.swing.JButton();
        editBtn_Guest = new javax.swing.JButton();
        delBtn_Guest = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        add_dialog.setMinimumSize(new java.awt.Dimension(600, 400));
        add_dialog.getContentPane().setLayout(new javax.swing.BoxLayout(add_dialog.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thêm Khách Hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_idlb.setText("Mã khách hàng");
        jPanel5.add(add_idlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        add_quantitylb.setText("Email");
        jPanel5.add(add_quantitylb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        add_namelb.setText("Tên khách hàng");
        jPanel5.add(add_namelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        add_brandlb.setText("Địa chỉ");
        jPanel5.add(add_brandlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        add_pricelb.setText("Số điện thoại");
        jPanel5.add(add_pricelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        add_emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_emailTextActionPerformed(evt);
            }
        });
        jPanel5.add(add_emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 190, -1));

        add_idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_idTextActionPerformed(evt);
            }
        });
        jPanel5.add(add_idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, -1));

        add_nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_nameTextActionPerformed(evt);
            }
        });
        jPanel5.add(add_nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 190, -1));

        add_addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_addressTextActionPerformed(evt);
            }
        });
        jPanel5.add(add_addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 190, -1));

        add_SdtText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_SdtTextActionPerformed(evt);
            }
        });
        jPanel5.add(add_SdtText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 190, -1));

        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jButton3.setText("Thêm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        add_dialog.getContentPane().add(jPanel4);

        edit_dialog.setMinimumSize(new java.awt.Dimension(600, 400));
        edit_dialog.getContentPane().setLayout(new javax.swing.BoxLayout(edit_dialog.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sửa Khách Hàng");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_idlb1.setText("Mã khách hàng");
        jPanel8.add(add_idlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        add_quantitylb1.setText("Email");
        jPanel8.add(add_quantitylb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        add_namelb1.setText("Tên khách hàng");
        jPanel8.add(add_namelb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        add_brandlb1.setText("Địa chỉ");
        jPanel8.add(add_brandlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        add_pricelb1.setText("Số điện thoại");
        jPanel8.add(add_pricelb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        edit_emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_emailTextActionPerformed(evt);
            }
        });
        jPanel8.add(edit_emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 190, -1));

        edit_nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_nameTextActionPerformed(evt);
            }
        });
        jPanel8.add(edit_nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 190, -1));

        edit_addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_addressTextActionPerformed(evt);
            }
        });
        jPanel8.add(edit_addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 190, -1));

        edit_SdtText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_SdtTextActionPerformed(evt);
            }
        });
        jPanel8.add(edit_SdtText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 190, -1));

        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jButton4.setText("Sửa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        edit_idLable.setText("jLabel4");
        jPanel8.add(edit_idLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, -1));

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        edit_dialog.getContentPane().add(jPanel6);

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new java.awt.BorderLayout());

        addBtn_Guest.setText("Thêm Khách Hàng");
        addBtn_Guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn_GuestActionPerformed(evt);
            }
        });

        editBtn_Guest.setText("Sửa");
        editBtn_Guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn_GuestActionPerformed(evt);
            }
        });

        delBtn_Guest.setText("Xóa");
        delBtn_Guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtn_GuestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn_Guest)
                .addGap(76, 76, 76)
                .addComponent(editBtn_Guest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(delBtn_Guest)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn_Guest)
                    .addComponent(editBtn_Guest)
                    .addComponent(delBtn_Guest))
                .addGap(28, 28, 28))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý khách hàng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Khách Hàng", "Họ tên Khách Hàng", "Địa chỉ", "Số điện thoại", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void editBtn_GuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn_GuestActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "Chọn Sản Phẩm cần sửa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{
        edit_dialog.setVisible(true);
        edit_dialog.setSize(600,500);
        edit_idLable.setText(listGuest.get(jTable1.getSelectedRow()).getID());
        }
    }//GEN-LAST:event_editBtn_GuestActionPerformed

    private void add_emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_emailTextActionPerformed

    private void add_idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_idTextActionPerformed

    private void add_nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_nameTextActionPerformed

    private void add_addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_addressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_addressTextActionPerformed

    private void add_SdtTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_SdtTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_SdtTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        add_dialog.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (add_idText.getText().isEmpty() || add_nameText.getText().isEmpty() || add_addressText.getText().isEmpty()|| add_SdtText.getText().isEmpty() || add_emailText.getText().isEmpty()) {
            // Nếu có trường nào rỗng, hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            // Nếu tất cả các trường đều có dữ liệu
            ArrayList<String> namelist = new ArrayList<>();
            for(Guest name : listGuest){
                namelist.add(name.getID());
            }
            // Kiểm tra nếu ID đã tồn tại
            if (namelist.contains(add_idText.getText())) {
                // Hiển thị thông báo lỗi nếu ID trùng
                JOptionPane.showMessageDialog(null, "ID đã tồn tại! Vui lòng nhập ID khác.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                // Nếu ID không trùng, thực hiện hành động khác (ví dụ: thêm ID mới)
                JOptionPane.showMessageDialog(null, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Guest g = new Guest(add_idText.getText(), add_nameText.getText(), add_addressText.getText(),add_SdtText.getText(), add_emailText.getText());
                gDAO.addGuest(g);
                add_dialog.dispose();
                setTable();
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void edit_emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_emailTextActionPerformed

    private void edit_nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_nameTextActionPerformed

    private void edit_addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_addressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_addressTextActionPerformed

    private void edit_SdtTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_SdtTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_SdtTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        add_dialog.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       if (edit_nameText.getText().isEmpty() || edit_SdtText.getText().isEmpty()|| edit_addressText.getText().isEmpty() || edit_emailText.getText().isEmpty()) {
                    // Nếu có trường nào rỗng, hiển thị thông báo lỗi
                    JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                } else {
            JOptionPane.showMessageDialog(null, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            Guest g = new Guest(edit_idLable.getText(),edit_nameText.getText(), edit_SdtText.getText(),edit_addressText.getText(),edit_emailText.getText());
            gDAO.updateGuest(edit_idLable.getText(),g);
            edit_dialog.dispose();
            setTable();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void addBtn_GuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn_GuestActionPerformed
        // TODO add your handling code here:
        add_dialog.setVisible(true);
        add_dialog.setSize(600,500);
        
    }//GEN-LAST:event_addBtn_GuestActionPerformed

    private void delBtn_GuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtn_GuestActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "Chọn Sản Phẩm cần sửa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{
            gDAO.deleteGuest(listGuest.get(jTable1.getSelectedRow()).getID());
            JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            setTable();
        }
    }//GEN-LAST:event_delBtn_GuestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn_Guest;
    private javax.swing.JTextField add_SdtText;
    private javax.swing.JTextField add_addressText;
    private javax.swing.JLabel add_brandlb;
    private javax.swing.JLabel add_brandlb1;
    private javax.swing.JDialog add_dialog;
    private javax.swing.JTextField add_emailText;
    private javax.swing.JTextField add_idText;
    private javax.swing.JLabel add_idlb;
    private javax.swing.JLabel add_idlb1;
    private javax.swing.JTextField add_nameText;
    private javax.swing.JLabel add_namelb;
    private javax.swing.JLabel add_namelb1;
    private javax.swing.JLabel add_pricelb;
    private javax.swing.JLabel add_pricelb1;
    private javax.swing.JLabel add_quantitylb;
    private javax.swing.JLabel add_quantitylb1;
    private javax.swing.JButton delBtn_Guest;
    private javax.swing.JButton editBtn_Guest;
    private javax.swing.JTextField edit_SdtText;
    private javax.swing.JTextField edit_addressText;
    private javax.swing.JDialog edit_dialog;
    private javax.swing.JTextField edit_emailText;
    private javax.swing.JLabel edit_idLable;
    private javax.swing.JTextField edit_nameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
