package views;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


import dao.StaffDAO;
import dao.UserDAO;
import java.awt.Window;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Staff;
import model.User;
import views.LoginForm;

/**
 *
 * @author abc
 */
public class InforUser extends javax.swing.JPanel {
    private UserDAO uDAO= new UserDAO();
    private StaffDAO sDAO = new StaffDAO();
    private String idUser;
    

    /**
     * Creates new form InforUser
     */
    public InforUser() {
        initComponents();
        UserNameLable.setText(LoginForm.username); 
        idUser = uDAO.getIdByUserName(LoginForm.username);
        Staff staff = sDAO.getStaffByIdUser(idUser);
        NameLable.setText(staff.getName());
        SDTLable.setText(staff.getSdt());
        EmailLable.setText(staff.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit_UserDetail = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        edit_detail_Username = new javax.swing.JLabel();
        add_namelb = new javax.swing.JLabel();
        add_brandlb = new javax.swing.JLabel();
        add_pricelb = new javax.swing.JLabel();
        edit_detail_Name = new javax.swing.JTextField();
        edit_detail_SDT = new javax.swing.JTextField();
        edit_detail_Email = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        add_idlb2 = new javax.swing.JLabel();
        edit_password = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        add_idlb1 = new javax.swing.JLabel();
        add_namelb1 = new javax.swing.JLabel();
        add_brandlb1 = new javax.swing.JLabel();
        add_pricelb1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        pw_UserNameLable = new javax.swing.JLabel();
        pw_ConfirmNewPasswordText = new javax.swing.JPasswordField();
        pw_OldPasswordText1 = new javax.swing.JPasswordField();
        pw_NewPasswordText = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        UserNameLable = new javax.swing.JLabel();
        NameLable = new javax.swing.JLabel();
        EmailLable = new javax.swing.JLabel();
        SDTLable = new javax.swing.JLabel();

        edit_UserDetail.setMinimumSize(new java.awt.Dimension(600, 400));
        edit_UserDetail.getContentPane().setLayout(new javax.swing.BoxLayout(edit_UserDetail.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sửa thông tin tài khoản");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edit_detail_Username.setText("Tên Tài khoản");
        jPanel5.add(edit_detail_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, -1));

        add_namelb.setText("Tên người dùng");
        jPanel5.add(add_namelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        add_brandlb.setText("Số điện thoại");
        jPanel5.add(add_brandlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        add_pricelb.setText("Email");
        jPanel5.add(add_pricelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        edit_detail_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_detail_NameActionPerformed(evt);
            }
        });
        jPanel5.add(edit_detail_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 190, -1));

        edit_detail_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_detail_SDTActionPerformed(evt);
            }
        });
        jPanel5.add(edit_detail_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 190, -1));

        edit_detail_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_detail_EmailActionPerformed(evt);
            }
        });
        jPanel5.add(edit_detail_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 190, -1));

        jButton4.setText("Hủy");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jButton5.setText("Sửa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        add_idlb2.setText("Tên đăng nhập");
        jPanel5.add(add_idlb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        edit_UserDetail.getContentPane().add(jPanel4);

        edit_password.setMinimumSize(new java.awt.Dimension(600, 400));
        edit_password.getContentPane().setLayout(new javax.swing.BoxLayout(edit_password.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Đổi mật khẩu");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_idlb1.setText("Tên đăng nhập");
        jPanel8.add(add_idlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        add_namelb1.setText("Mật khẩu cũ");
        jPanel8.add(add_namelb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        add_brandlb1.setText("Mật khẩu mới");
        jPanel8.add(add_brandlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        add_pricelb1.setText("Xác nhận lại mật khẩu");
        jPanel8.add(add_pricelb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jButton6.setText("Hủy");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jButton7.setText("Đổi");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        pw_UserNameLable.setText("jLabel4");
        jPanel8.add(pw_UserNameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, -1));
        jPanel8.add(pw_ConfirmNewPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 190, -1));

        pw_OldPasswordText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw_OldPasswordText1ActionPerformed(evt);
            }
        });
        jPanel8.add(pw_OldPasswordText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 190, -1));

        pw_NewPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw_NewPasswordTextActionPerformed(evt);
            }
        });
        jPanel8.add(pw_NewPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 190, -1));

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        edit_password.getContentPane().add(jPanel6);

        setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Đăng xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tên đăng nhập");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tên người dùng");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Số điện thoại");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Email");

        jButton2.setText("Sửa thông tin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Đổi mật khẩu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        UserNameLable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UserNameLable.setText("UserName");

        NameLable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NameLable.setText("UserName");

        EmailLable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailLable.setText("UserName");

        SDTLable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SDTLable.setText("UserName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SDTLable, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailLable, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(305, 305, 305))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UserNameLable))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NameLable))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SDTLable))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EmailLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Đóng tất cả các JFrame và JDialog đang mở
        for (Window window : Window.getWindows()) {
            // Kiểm tra nếu cửa sổ là JFrame hoặc JDialog
            if (window instanceof JFrame || window instanceof JDialog) {
                window.dispose();  // Đóng cửa sổ
            }
        }
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
//Mở cửa sổ đổi mật khẩu
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pw_ConfirmNewPasswordText.removeAll();
        pw_NewPasswordText.removeAll();
        pw_OldPasswordText1.removeAll();
        edit_password.setVisible(true);
        edit_password.setSize(600,500);
        pw_UserNameLable.setText(LoginForm.username);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void edit_detail_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_detail_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_detail_NameActionPerformed

    private void edit_detail_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_detail_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_detail_SDTActionPerformed

    private void edit_detail_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_detail_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_detail_EmailActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        edit_UserDetail.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (edit_detail_Name.getText().isEmpty() || edit_detail_SDT.getText().isEmpty()|| edit_detail_Email.getText().isEmpty() ) {
            // Nếu có trường nào rỗng, hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if(edit_detail_SDT.getText().length()>11){
            //Kiểm tra sdt hợp lệ
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }else {
            // Nếu tất cả các trường đều có dữ liệu
            Staff staff = new  Staff(edit_detail_Name.getText(), edit_detail_SDT.getText(), edit_detail_Email.getText(), idUser);
            sDAO.updateStaffByIdUser(staff);
            JOptionPane.showMessageDialog(null, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            edit_UserDetail.dispose();

            
            }

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        edit_UserDetail.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String old_pw= new String (pw_OldPasswordText1.getPassword());
        String npw= new String(pw_ConfirmNewPasswordText.getPassword());
        String cpw= new String(pw_ConfirmNewPasswordText.getPassword());
        if (pw_ConfirmNewPasswordText.getPassword().length==0 || pw_NewPasswordText.getPassword().length ==0|| pw_OldPasswordText1.getPassword().length==0) {
            // Nếu có trường nào rỗng, hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ mật khẩu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }else if(!uDAO.getPasswordById(Integer.parseInt(idUser)).equals(old_pw)) {
            JOptionPane.showMessageDialog(null, "Mật khẩu không đúng", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if(!npw.equals(cpw)) {
            JOptionPane.showMessageDialog(null, "Xác nhận mật khẩu mới không khớp", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }     else {
            uDAO.updatePassword(Integer.parseInt(idUser),cpw );
            JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            edit_password.dispose();
        }
    }//GEN-LAST:event_jButton7ActionPerformed
//Mở cửa sổ sửa thông tin tài khoản
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        edit_UserDetail.setVisible(true);
        edit_UserDetail.setSize(600,500);
        edit_detail_Username.setText(UserNameLable.getText());
        Staff staff = sDAO.getStaffById(idUser);
        edit_detail_Name.setText(staff.getName());
        edit_detail_SDT.setText(staff.getSdt());
        edit_detail_Email.setText(staff.getEmail());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pw_OldPasswordText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw_OldPasswordText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw_OldPasswordText1ActionPerformed

    private void pw_NewPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw_NewPasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw_NewPasswordTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLable;
    private javax.swing.JLabel NameLable;
    private javax.swing.JLabel SDTLable;
    private javax.swing.JLabel UserNameLable;
    private javax.swing.JLabel add_brandlb;
    private javax.swing.JLabel add_brandlb1;
    private javax.swing.JLabel add_idlb1;
    private javax.swing.JLabel add_idlb2;
    private javax.swing.JLabel add_namelb;
    private javax.swing.JLabel add_namelb1;
    private javax.swing.JLabel add_pricelb;
    private javax.swing.JLabel add_pricelb1;
    private javax.swing.JDialog edit_UserDetail;
    private javax.swing.JTextField edit_detail_Email;
    private javax.swing.JTextField edit_detail_Name;
    private javax.swing.JTextField edit_detail_SDT;
    private javax.swing.JLabel edit_detail_Username;
    private javax.swing.JDialog edit_password;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField pw_ConfirmNewPasswordText;
    private javax.swing.JPasswordField pw_NewPasswordText;
    private javax.swing.JPasswordField pw_OldPasswordText1;
    private javax.swing.JLabel pw_UserNameLable;
    // End of variables declaration//GEN-END:variables
}
