/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import dao.ProductDAO;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Product;

/**
 *
 * @author abc
 */
public class ProductPanel extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    
    private ProductDAO pDAO = new ProductDAO();
    private List<Product> products = pDAO.getAllProducts() ;
    public ProductPanel() {
        initComponents();
        setTable();
    }
    
    private void setTable() {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        jTable1.setModel(defaultTableModel);
        ListSelectionModel listSelectionModel = jTable1.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        defaultTableModel.addColumn("STT");
        defaultTableModel.addColumn("Mã Sản Phẩm");
        defaultTableModel.addColumn("Tên Laptop");
        defaultTableModel.addColumn("Tên hãng sản xuất");
        defaultTableModel.addColumn("Giá bán");
        defaultTableModel.addColumn("Số lượng");
        products = pDAO.getAllProducts();

        // Duyệt qua danh sách products và thêm vào bảng
        int stt = 1; // Biến đánh số thứ tự
        for (Product product : products) {
            Object[] row = new Object[6];
            row[0] = stt++;  // Số thứ tự
            row[1] = product.getID();
            row[2] = product.getProductName();
            row[3] = product.getBrandName();
            row[4] = product.getPrice();
            row[5] = product.getQuantity();
            defaultTableModel.addRow(row); // Thêm hàng vào bảng
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        add_idlb = new javax.swing.JLabel();
        add_quantitylb = new javax.swing.JLabel();
        add_namelb = new javax.swing.JLabel();
        add_brandlb = new javax.swing.JLabel();
        add_pricelb = new javax.swing.JLabel();
        add_quantityText = new javax.swing.JTextField();
        add_idText = new javax.swing.JTextField();
        add_nameText = new javax.swing.JTextField();
        add_brandText = new javax.swing.JTextField();
        add_priceText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        edit_nameText = new javax.swing.JTextField();
        edit_brandText = new javax.swing.JTextField();
        edit_quantityText = new javax.swing.JTextField();
        edit_priceText = new javax.swing.JTextField();
        edit_idlb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addBtn_Product = new javax.swing.JButton();
        editBtn_Product = new javax.swing.JButton();
        delBtn_Product = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jDialog2.setMinimumSize(new java.awt.Dimension(600, 400));
        jDialog2.getContentPane().setLayout(new javax.swing.BoxLayout(jDialog2.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thêm Sản Phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_idlb.setText("Mã sản phẩm");
        jPanel5.add(add_idlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        add_quantitylb.setText("Số lượng");
        jPanel5.add(add_quantitylb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        add_namelb.setText("Tên sản phẩm");
        jPanel5.add(add_namelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        add_brandlb.setText("Tên hãng sản xuất");
        jPanel5.add(add_brandlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        add_pricelb.setText("Giá bán");
        jPanel5.add(add_pricelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        add_quantityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_quantityTextActionPerformed(evt);
            }
        });
        jPanel5.add(add_quantityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 190, -1));

        add_idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_idTextActionPerformed(evt);
            }
        });
        jPanel5.add(add_idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, -1));

        add_nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_nameTextActionPerformed(evt);
            }
        });
        jPanel5.add(add_nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 190, -1));

        add_brandText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_brandTextActionPerformed(evt);
            }
        });
        jPanel5.add(add_brandText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 190, -1));

        add_priceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_priceTextActionPerformed(evt);
            }
        });
        jPanel5.add(add_priceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 190, -1));

        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jButton3.setText("Thêm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jDialog2.getContentPane().add(jPanel4);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sửa sản phẩm");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jDialog1.getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));

        jLabel9.setText("Mã Sản Phẩm");

        jLabel10.setText("Tên Sản Phẩm");

        jLabel11.setText("Tên hãng sản xuất");

        jLabel12.setText("Giá bán");

        jLabel13.setText("Số lượng");

        edit_nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_nameTextActionPerformed(evt);
            }
        });

        edit_brandText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_brandTextActionPerformed(evt);
            }
        });

        edit_quantityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_quantityTextActionPerformed(evt);
            }
        });

        edit_priceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_priceTextActionPerformed(evt);
            }
        });

        edit_idlb.setText("jLabel14");

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Hủy");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edit_quantityText, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(edit_brandText, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(edit_nameText, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(edit_priceText, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(edit_idlb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton2)
                        .addGap(49, 49, 49)
                        .addComponent(jButton4)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(edit_idlb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(edit_nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(edit_brandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(edit_priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(edit_quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jDialog1.getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý sản phẩm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        addBtn_Product.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addBtn_Product.setText("Thêm sản phẩm");
        addBtn_Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn_ProductActionPerformed(evt);
            }
        });

        editBtn_Product.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editBtn_Product.setText("Sửa sản phẩm");
        editBtn_Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn_ProductActionPerformed(evt);
            }
        });

        delBtn_Product.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        delBtn_Product.setText("Xóa sản phẩm");
        delBtn_Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtn_ProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(addBtn_Product)
                .addGap(37, 37, 37)
                .addComponent(editBtn_Product)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delBtn_Product)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn_Product)
                    .addComponent(editBtn_Product)
                    .addComponent(delBtn_Product))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Laptop", "Tên hãng sản xuất", "Giá bán", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtn_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn_ProductActionPerformed
        // TODO add your handling code here:
        jDialog2.setVisible(true);
        jDialog2.setSize(600,500);
    }//GEN-LAST:event_addBtn_ProductActionPerformed

    private void editBtn_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn_ProductActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "Chọn Sản Phẩm cần sửa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{
        jDialog1.setVisible(true);
        jDialog1.setSize(600,500);
        edit_idlb.setText(products.get(jTable1.getSelectedRow()).getID());
    }//GEN-LAST:event_editBtn_ProductActionPerformed
    }
    private void add_quantityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_quantityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_quantityTextActionPerformed

    private void add_idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_idTextActionPerformed

    private void add_nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_nameTextActionPerformed

    private void add_brandTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_brandTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_brandTextActionPerformed

    private void add_priceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_priceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_priceTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jDialog2.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void edit_nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_nameTextActionPerformed

    private void edit_brandTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_brandTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_brandTextActionPerformed

    private void edit_quantityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_quantityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_quantityTextActionPerformed

    private void edit_priceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_priceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_priceTextActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (add_idText.getText().isEmpty() || add_nameText.getText().isEmpty() || add_brandText.getText().isEmpty()|| add_priceText.getText().isEmpty() || add_quantityText.getText().isEmpty()) {
                    // Nếu có trường nào rỗng, hiển thị thông báo lỗi
                    JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Nếu tất cả các trường đều có dữ liệu
                     ArrayList<String> namelist = new ArrayList<>();
        for(Product name : products){
            namelist.add(name.getID());
        }
        // Kiểm tra nếu ID đã tồn tại
        if (namelist.contains(add_idText.getText())) {
            // Hiển thị thông báo lỗi nếu ID trùng
            JOptionPane.showMessageDialog(null, "ID đã tồn tại! Vui lòng nhập ID khác.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            // Nếu ID không trùng, thực hiện hành động khác (ví dụ: thêm ID mới)
            JOptionPane.showMessageDialog(null, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            Product p = new Product(add_idText.getText(), add_nameText.getText(), add_brandText.getText(),Double.parseDouble(add_priceText.getText()), Integer.parseInt(add_quantityText.getText()));
            pDAO.addProduct(p);
            jDialog2.dispose();
            setTable();
        }
        
                }
              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (edit_nameText.getText().isEmpty() || edit_priceText.getText().isEmpty()|| edit_quantityText.getText().isEmpty() || edit_brandText.getText().isEmpty()) {
                    // Nếu có trường nào rỗng, hiển thị thông báo lỗi
                    JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                } else {
            JOptionPane.showMessageDialog(null, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            Product p = new Product(edit_idlb.getText(), edit_nameText.getText(), edit_brandText.getText(),Double.parseDouble(edit_priceText.getText()), Integer.parseInt(edit_quantityText.getText()));
            pDAO.updateProduct(edit_idlb.getText(), p);
            jDialog1.dispose();
            setTable();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void delBtn_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtn_ProductActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "Chọn Sản Phẩm cần sửa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{
            pDAO.deleteProduct(products.get(jTable1.getSelectedRow()).getID());
            JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            setTable();
        }
    }//GEN-LAST:event_delBtn_ProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn_Product;
    private javax.swing.JTextField add_brandText;
    private javax.swing.JLabel add_brandlb;
    private javax.swing.JTextField add_idText;
    private javax.swing.JLabel add_idlb;
    private javax.swing.JTextField add_nameText;
    private javax.swing.JLabel add_namelb;
    private javax.swing.JTextField add_priceText;
    private javax.swing.JLabel add_pricelb;
    private javax.swing.JTextField add_quantityText;
    private javax.swing.JLabel add_quantitylb;
    private javax.swing.JButton delBtn_Product;
    private javax.swing.JButton editBtn_Product;
    private javax.swing.JTextField edit_brandText;
    private javax.swing.JLabel edit_idlb;
    private javax.swing.JTextField edit_nameText;
    private javax.swing.JTextField edit_priceText;
    private javax.swing.JTextField edit_quantityText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
